NiCris.Web/Controllers/BizMsgMonitorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NiCris.Web.Controllers
{
    public class BizMsgMonitorController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Your BizMsg Monitor page.";
            return View();
        }
    }
}

NiCris.Web/Controllers/TaskController.cs
using NiCris.BusinessObjects;
using NiCris.DataAccess.Dapper;
using NiCris.DataAccess.Interfaces;
using NiCris.Web.Hubs;
using SignalR;
using SignalR.Hubs;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace NiCris.Web.Controllers
{
    public class TaskController : Controller
    {
        // FIELDS
        private static readonly Random _rnd = new Random();
        ITaskRepository _taskRepository;
        IHubContext _context;

        // C~tors
        public TaskController()
        {
            _taskRepository = new TaskRepository();
            _context = GlobalHost.ConnectionManager.GetHubContext<TaskHub>();
        }

        // VIEWS
        public ActionResult Index()
        {
            ViewBag.ClientName = "user-" + _rnd.Next(10000, 99999);
            return View();
        }

        // JSON PROVIDERS
        [HttpPost]
        public JsonResult TaskList()
        {
            try
            {
                var taskRespo = new TaskRepository();
                List<TaskEx> tasks = taskRespo.GetAllTasks();
                return Json(new { Result = "OK", Records = tasks });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult CreateTask(TaskEx task)
        {
            try
            {
                // Validation
                if (!ModelState.IsValid)
                {
                    return Json(new { Result = "ERROR", Message = "Form is not valid! Please correct it and try again." });
                }

                var taskRespo = new TaskRepository();
                TaskEx addedTask = taskRespo.AddTask(task);

                // Inform all connected clients
                var clientName = Request["clientName"];
                Task.Factory.StartNew(
                    () =>
                    {
                        // var clients = Hub.GetClients<TaskHub>();
                        _context.Clients.RecCreated(clientName, task);
                    });

                // Return result to current (caller) client
                return Json(new { Result = "OK", Record = addedTask });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult UpdateTask(TaskEx task)
        {
            try
            {
                // Validation
                if (!ModelState.IsValid)
                {
                    return Json(new { Result = "ERROR", Message = "Form is not valid! Please correct it and try again." });
                }

                var taskRespo = new TaskRepository();
                taskRespo.UpdateTask(task);

                // Inform all connected clients
                var clientName = Request["clientName"];
                Task.Factory.StartNew(
                    () =>
                    {
                        // var clients = Hub.GetClients<TaskHub>();
                        _context.Clients.RecUpdated(clientName, task);
                    });

                // Return result to current (caller) client
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult DeleteTask(int id)
        {
            try
            {
                var taskRespo = new TaskRepository();
                taskRespo.DeleteTask(id);

                // Inform all connected clients
                var clientName = Request["clientName"];
                Task.Factory.StartNew(
                    () =>
                    {
                        // var clients = Hub.GetClients<TaskHub>();
                        _context.Clients.RecDeleted(clientName, id);
                    });

                // Return result to current (caller) client
                return Json(new { Result = "OK" });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

    }
}

NiCris.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>NiCris Dashboard - @ViewBag.Title</title>

    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />

    @Styles.Render("~/Content/Bootstrap")
    @Scripts.Render("~/bundles/modernizr")

    <link href="@Url.Content("~/Content/themes/redmond/jquery-ui-1.8.16.custom.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Scripts/jtable/themes/standard/blue/jtable_blue.css")" rel="stylesheet" type="text/css" />

    <script src="@Url.Content("~/Scripts/jquery-1.8.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.23.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jtable/jquery.jtable.min.js")" type="text/javascript"></script>

    <script src="~/Scripts/jquery.signalR-0.5.3.min.js" type="text/javascript"></script>
    <script src="/signalr/hubs" type="text/javascript"></script>

    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
            background: none repeat scroll 0 0 #EEE;
        }

        .aligntobottom {
            bottom: 0;
            position: absolute;
        }

        footer.container.navbar-fixed-top {
            top: auto;
            bottom: 9px;
        }

        div.rectangular-area {
            border: 1px solid #999;
            margin-top: 5px;
            margin-bottom: 5px;
            padding: 10px;
            background-color: #EEE;
        }

        #TableUpdates {
            height: 200px;
            overflow: auto;
        }

        .event-deleted {
            color: Red;
        }

        .event-updated {
            color: green;
        }

        .event-created {
            color: blue;
        }

        .event-message {
            color: rgb(117, 117, 117);
        }

        p.demo-info {
            font-size: 12px;
            color: rgb(44, 50, 230);
            font-weight: bold;
        }
    </style>
</head>

<body>

    <div class="navbar navbar-fixed-top navbar-inverse">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" style="padding:4px 5px 0px 0px" href="@Url.Action("Index", "Home")">
                    <span>
                        <img src="@Url.Content("~/Content/logo.png")" alt="logo" border="0"/></span>
                </a>
                <div class="nav-collapse">
                    <ul class="nav">
                        <li>@Html.ActionLink("Biz", "Index", "BizMsgMonitor")</li>
                        <li>@Html.ActionLink("Chat", "Index", "Chat")</li>
                        <li>@Html.ActionLink("Dashboard", "Index", "Task")</li>
                    </ul>
                </div>

                <form class="navbar-search pull-left">
                    <input type="text" class="search-query" placeholder="Search">
                </form>

                <!--/.nav-collapse -->
                <ul class="nav pull-right">
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li style="padding-top: 10px; padding-left: 15px"><i class="icon-user icon-white"></i>@User.Identity.Name</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container">
        @if (IsSectionDefined("featured"))
        {
            <div class="hero-unit">
                @RenderSection("featured", required: false)
            </div>
        }

        @RenderBody()

        <footer class="container navbar navbar-fixed-top">
            <hr>
            <p>© NiCris Dashboard 2012</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/Scripts/Bootstrap")
    @RenderSection("scripts", required: false)

</body>

</html>